# Generated by Django 4.1.3 on 2022-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='desc',
            field=models.CharField(max_length=280),
        ),
    ]
